In [3]:
import numpy as np
import sys
sys.path.append(r"C:\Users\gapar\OneDrive\Documents\GitHub\Logical-Clifford-Synthesis\new one")
from Algorithms.algorithm_1 import SymplecticOperations
#from helper_functions.helperfunctions import SymplecticMatrix
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

# Initialize the SymplecticOperations class
symplectic_ops = SymplecticOperations()
#symp_mat = SymplecticMatrix(3)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
# Define matrices X and Y
X = np.array([[1, 0,0,0], [0, 1,0,0],[0,0,1,0],[0,0,0,1]])
Y = np.array([[1,1,0,0], [0, 1,0,0],[0,0,1,0],[0,0,1,1]])


# Perform the symplectic matrix transformation
F, Transvecs = symplectic_ops.find_symp_mat_transvecs(X,Y)


# Print the results
print("Resulting F matrix:")
print(F)


Resulting F matrix:
[[1. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 1.]]


In [5]:
U = np.array([[1, 0 ,0 ,0],
 [0, 1, 0 ,0],
 [0 ,0, 0, 1]])

V = np.array([[1,1,0,0], [0, 1,0,0],[0,0,1,0],[0,0,1,1]])


# Perform the symplectic matrix transformation
F, Transvecs = symplectic_ops.find_symp_mat_transvecs(U,V)


# Print the results
print("Resulting F matrix:")
print(F)


Resulting F matrix:
[[0. 0. 0. 1.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [0. 0. 1. 0.]]


In [6]:
G_h1 =  np.array([
    [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
])

H_h1 = np.array([
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
    [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
])

# Perform the symplectic matrix transformation
F, Transvecs = symplectic_ops.find_symp_mat_transvecs(G_h1, H_h1)


# Print the results
print("Resulting F matrix:")
print(F)

Resulting F matrix:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
