In [93]:
import numpy as np
import sys
sys.path.append(r"C:\Users\gapar\Logical-Clifford-Synthesis")
from Algorithms.algorithm_1 import SymplecticOperations
from helper_functions.helperfunctions import SymplecticMatrix
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

# Initialize the SymplecticOperations class
symplectic_ops = SymplecticOperations()
symp_mat = SymplecticMatrix(3)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [94]:
# Define matrices X and Y
X = np.array([[1, 0,0,0], [0, 1,0,0],[0,0,1,0],[0,0,0,1]])
Y = np.array([[1,1,0,0], [0, 1,0,0],[0,0,1,0],[0,0,1,1]])


# Perform the symplectic matrix transformation
F, *_ = symplectic_ops.find_symp_mat_transvecs(X,Y)


# Print the results
print("Resulting F matrix:")
print(F)


Resulting F matrix:
[[1. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 1.]]


In [95]:
U = np.array([[1, 0 ,0 ,0],
 [0, 1, 0 ,0],
 [0 ,0, 0, 1]])

V = np.array([[1,1,0,0], [0, 1,0,0],[0,0,1,0],[0,0,1,1]])


# Perform the symplectic matrix transformation
F, Transvecs = symplectic_ops.find_symp_mat_transvecs(U,V)


# Print the results
print("Resulting F matrix:")
print(F)


Resulting F matrix:
[[0. 0. 0. 1.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [0. 0. 1. 0.]]
