In [57]:
import numpy as np
import sys
sys.path.append(r"C:\Users\gapar\Logical-Clifford-Synthesis")
from Algorithms.algorithm_1 import SymplecticOperations
from helper_functions.helperfunctions import SymplecticMatrix
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

# Initialize the SymplecticOperations class
symplectic_ops = SymplecticOperations()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [58]:
# Define matrices X and Y
X = np.array([[1, 0,0,0], [0, 1,0,0],[0,0,1,0],[0,0,0,1]])
Y = np.array([[1,1,0,0], [0, 1,0,0],[0,0,1,0],[0,0,1,1]])


# Perform the symplectic matrix transformation
F, *_ = symplectic_ops.find_symp_mat_transvecs(X,Y)


# Print the results
# print("Resulting F matrix:")
#print(F)


x_i
[1 0 0 0]
y_i
[1 1 0 0]
pick w_i
A
[[0. 0. 1. 0.]
 [0. 0. 1. 1.]]
b
[1 1]
x_it
[1. 0. 0. 0.]
y_i
[1 1 0 0]
Y[:i, :] []
n 2
w_i [0 0 1 0]
h_i1
[1 1 1 0]
h_i2
[1. 0. 1. 0.]
F
[[1. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 1. 0.]
 [1. 1. 1. 1.]]
x_i
[0 1 0 0]
y_i
[0 1 0 0]
x_it == y_i
x_i
[0 1 0 0]
y_i
[0 1 0 0]
F
[[1. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 1. 0.]
 [1. 1. 1. 1.]]
x_i
[0 0 1 0]
y_i
[0 0 1 0]
pick w_i
A
[[1. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]
b
[1 1 1 0]
x_it
[0. 1. 1. 0.]
y_i
[0 0 1 0]
Y[:i, :] [[1 1 0 0]
 [0 1 0 0]]
n 2
w_i [1 0 0 1]
h_i1
[1 0 1 1]
h_i2
[1. 1. 1. 1.]
F
[[1. 1. 0. 0.]
 [1. 1. 1. 1.]
 [0. 1. 1. 0.]
 [1. 0. 1. 1.]]
x_i
[0 0 0 1]
y_i
[0 0 1 1]
pick w_i
A
[[1. 1. 1. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]
b
[1 1 0 1 0]
x_it
[1. 0. 1. 1.]
y_i
[0 0 1 1]
Y[:i, :] [[1 1 0 0]
 [0 1 0 0]
 [0 0 1 0]]
n 2
w_i [1 1 1 1]
h_i1
[1 1 0 0]
h_i2
[0. 1. 0. 0.]
F
[[1. 1. 0. 0.]
 [1. 0. 1. 1.]
 [1. 0. 1. 0.]
 [1. 1. 1. 1.]]
